name: nvchecker

on:
  push:
    branches:
      - master
    paths:
      - "config.toml"
  pull_request:
    branches:
      - master
    paths:
      - "config.toml"
  schedule:
    - cron: "0 */3 * * *"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  check-new-versions:
    name: Check New Versions
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sunlei/nvchecker:pr-1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    steps:
      - uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          echo "LOG_FILE=nvchecker_$(date +'%Y-%m-%d_%H-%M-%S').log" >> $GITHUB_ENV

      - name: Check version
        run: |
          # echo "VERSIONS_COMPARE=$(docker exec nvchecker-app nvcmp config.toml 2>&1)" >> $GITHUB_ENV

          # touch old_ver.json new_ver.json

          nvchecker --file config.toml 2>&1 | tee ${{ env.LOG_FILE }}
          nvcmp --file config.toml > result.tmp
          nvtake --file config.toml --all

      - name: Send Email
        # -F attachment=@${{ env.LOG_FILE }} \
        run: |
          LOG=$(cat ${{ env.LOG_FILE }})
          RESULT=$(cat result.tmp)
          DATE=$(date +"%Y-%m-%d")
          [[ ! -z $RESULT ]] \
          && curl \
            -s \
            --user 'api:${{ secrets.MAILGUN_API_KEY }}' \
            https://api.mailgun.net/v3/${{ secrets.MAILGUN_DOMAIN_NAME }}/messages \
            -F from='nvchecker <postmaster@${{ secrets.MAILGUN_DOMAIN_NAME }}>' \
            -F to=${{ secrets.EMAIL_TO }} -F subject="New version check result · $DATE" \
            -F text="$RESULT" --form-string html="<html><pre><code>$RESULT</code></pre><hr /><pre><code>$LOG</code></pre></html>" \
          || echo "No new versions"
          rm -f result.tmp ${{ env.LOG_FILE }}

      - name: Commit version record files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: Apply version record files changes"

          # branch: ${{ github.head_ref }}
          branch: master
          commit_options: "--no-verify --signoff"
          file_pattern: ./*.txt
          repository: .

          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
          commit_author: GitHub Actions <actions@github.com>

      # - name: nvchecker-action
      #   id: nvchecker-action
      #   uses: guizai/nvchecker-action@master
      #   with:
      #     source-file: 'config.toml'
